//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Uichessborad_prefab
    {
        public const string BundleName = "uichessborad_prefab";
        public const string UIChessBorad = "UIChessBorad";
    }
    public class Uifadepanel_prefab
    {
        public const string BundleName = "uifadepanel_prefab";
        public const string UIFadePanel = "UIFadePanel";
    }
}
